# Generated by Django 4.2.3 on 2023-08-21 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_event', models.CharField(max_length=100, verbose_name='Название')),
                ('announcement_event', models.CharField(max_length=150, verbose_name='Текст для карточки')),
                ('picture_event', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Изображение')),
                ('date_event', models.DateField(verbose_name='Дата и время')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
            },
        ),
    ]
