# Generated by Django 4.2.3 on 2023-07-12 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Aticles',
            new_name='Articles',
        ),
    ]
